### ISSUE TITLE
Standardize Variant Tracker Sheets

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/clinvar-ingest-reports#60]
- [x] Update all tracker buttons to updated format.
- [x] Align columns.
- [x] Freeze headers/trackers.
- [x] Set up remaining VCEPs' tracker sheets.

**Comment by RyanFWebb** [comment]
- [ ] ACADVL
- [ ] Brain Malformations
- [ ] Cardiomyopathy
- [ ] CDH1
- [ ] Cerebral Creatine Deficiency Syndromes
- [ ] DICER1
- [ ] FBN1
- [ ] FH
- [ ] Glaucoma
- [ ] HL
- [ ] Hereditary B/P/O Cancer
- [ ] InSiGHT
- [ ] Lysosomal Diseases
- [ ] Malignant Hyperthermia Susceptibility
- [ ] Mitochondrial Disease
- [ ] Monogenic Diabetes
- [ ] Myeloid Malignancy
- [ ] Phenylketonuria
- [ ] Platelet Disorders
- [ ] PTEN
- [ ] RAS
- [ ] Rett Angelman
- [ ] Simons GC
- [ ] TP53

**Comment by RyanFWebb** [comment]
The FH VCEP Tracker sheet is not populating the submitted_submitter_abbrev column in the alerts sheet.

**Comment by RyanFWebb** [comment]
The Myeloid Malignancy VCEP Tracker sheet is not populating the submitted_submitter_abbrev column in the alerts sheet.

**Comment by larrybabb** [comment]
I fixed the FH and MM VCEP tracker sheets so that the submitter abbrev cols are showing now.
