### ISSUE TITLE
GenomeConnect MVP Variation Tracker

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#7]
This Epic covers the full transition from the Excel-based reports to Google sheet-based reports fed by the ClinVar ingest data.

- [x] Update Excel-based reports to include GenomeConnect GenomeConnect - Invitae Patient Insights Network and 
GenomeConnect - Brain Gene Registry ClinVar submitters as an interim solution to deliver data to the GenomeConnect team as soon as possible

- [ ] Replace Excel-based reports with Google-sheet based reports fed by ClinVar ingest data

- [ ] Enhance new GenomeConnect reports with requested features 

- [ ] Provide a new Google sheet-based report for GenomeConnect - Simons Searchlight as requested by GenomeConnect team
